# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.

services:
  reuse-api-worker:
    container_name: reuse-api-worker
    image: reuse-api-worker
    restart: always
    build: .
    expose:
      - "22"
    volumes: # Docker in container uses the host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    networks: # Hook onto REUSE API network
      - reuse-api-net

networks:
  reuse-api-net:
    external: true
