---
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.

- name: Setup instance to delegate REUSE checks to
  hosts: reuse_api_servers
  remote_user: root
  vars:
    api_env: "{{ lookup('env', 'API_ENV') }}"

  tasks:

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: true
        update_cache: true
        force_apt_get: true
      tags:
        - upgrade

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - cron
          - docker.io
          - git
          - python3
          - python3-docker

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true
      when: api_env != "devel"

    - name: Create reuse user
      user:
        name: reuse
        shell: /bin/rbash
        groups: docker

    - name: Set authorized_keys for reuse user
      authorized_key:
        user: reuse
        state: present
        key: "{{ item }}"
        key_options: 'command="reuse_lint_repo ${SSH_ORIGINAL_COMMAND#* }",no-port-forwarding,no-X11-forwarding,no-pty'
      with_file:
        - files/reuse_ed25519.pub

    - name: If developing, set additional authorized_keys for root user
      when: api_env == "devel"
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
        key_options: 'command="reuse_lint_repo ${SSH_ORIGINAL_COMMAND#* }",no-port-forwarding,no-X11-forwarding,no-pty'
      with_file:
        - files/test_ed25519.pub

    - name: Build reuse-api-worker-runner Docker image
      raw: |
        docker pull fsfe/reuse
        git clone --depth 1 https://git.fsfe.org/reuse/api-worker.git
        docker build --no-cache -t reuse-api-worker-runner api-worker/docker-image/
        rm -rf api-worker/
        docker image prune --force

      tags:
        - docker
        - upgrade
      when: api_env != "devel"

    - name: Deploy wrapper script
      copy:
        src: files/reuse_lint_repo.py
        dest: /usr/local/bin/reuse_lint_repo
        owner: reuse
        group: root
        mode: "0755"
      tags: script

    - name: Set cronjob to prune unused Docker networks
      cron:
        name: "Prune unused Docker networks"
        special_time: hourly
        job: "docker network prune -f"
