---
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.

- name: Setup instance to delegate REUSE checks to
  hosts: reuse_api_servers
  remote_user: root
  vars:
    api_env: "{{ lookup('env', 'API_ENV') }}"

  tasks:

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
      tags:
      - upgrade

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - cron
        - docker.io
        - git
        - xxhash

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
      when: api_env != "devel"

    - name: Create reuse user
      user:
        name: reuse
        shell: /bin/rbash
        groups: docker

    - name: Set authorized_keys for reuse user
      authorized_key:
        user: reuse
        state: present
        key: "{{ item }}"
        key_options: 'command="reuse-lint-repo ${SSH_ORIGINAL_COMMAND#* }",no-port-forwarding,no-X11-forwarding,no-pty'
      with_file:
        - files/reuse_ed25519.pub

    - name: Set additional authorized_keys for root user if devel environment
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
        key_options: 'command="reuse-lint-repo ${SSH_ORIGINAL_COMMAND#* }",no-port-forwarding,no-X11-forwarding,no-pty'
      with_file:
        - files/test_ed25519.pub
      when: api_env == "devel"

    - name: Build reuse-api-worker-runner Docker image
      raw: |
        docker pull fsfe/reuse:latest
        git clone https://git.fsfe.org/reuse/api-worker.git reuse-api
        docker build --no-cache -t reuse-api-worker-runner reuse-api/docker-image/
        rm -rf reuse-api/
        docker rmi $(docker images | grep "<none>" | awk "{print \$3}") || true
      tags:
      - docker
      - upgrade
      when: api_env != "devel"

    - name: Deploy wrapper script
      copy:
        src: files/reuse-lint-repo
        dest: /usr/local/bin/reuse-lint-repo
        owner: reuse
        group: root
        mode: "0755"
      tags: script

    - name: Set cronjob to prune unused Docker networks
      cron:
        name: "Prune unused Docker networks"
        special_time: hourly
        job: "docker network prune -f"
