#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.

REPO="${1}"
REUSE_OPT_GLOBAL="${2}"
REUSE_OPT_LINT="${3}"
TMP="$(mktemp)"

if [ -z ${REPO} ]; then
  echo "No repo URL provided"
  exit 41
fi

# Create ENV file containing REUSE args
echo "REUSE_OPT_GLOBAL=${REUSE_OPT_GLOBAL}" > $TMP
echo "REUSE_OPT_LINT=${REUSE_OPT_LINT}" >> $TMP

# Extract name for docker container
DNAME="$(basename "$(dirname "${REPO}")")__$(basename "${REPO}")"

# Run docker image and return status
docker run --env-file $TMP --name "${DNAME}" --rm reuse-api "${REPO}"
status=$?

rm $TMP

exit $status
