#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.

# TODO: rewrite to Python with proper args

REPO="${1}"
REUSE_GLOBAL_OPTIONS="${2}"
REUSE_LINT_OPTIONS="${3}"
REUSE_SPDX_OPTIONS="${4}"
TMP="$(mktemp)"

LOGFILE="/tmp/reuse.log"

log () {
  echo "[$(date +"%Y-%m-%d %H:%M:%S")] $*" >> "${LOGFILE}"
}

log "Check repo ${REPO} with optional arguments: global:${REUSE_GLOBAL_OPTIONS} lint:${REUSE_LINT_OPTIONS} spdx:${REUSE_SPDX_OPTIONS}"

# Test if repo URL provided
if [[ -z ${REPO} ]]; then
  log "No repo URL provided"
  exit 41
fi
# Test if API worker runner image exists
if [[ "$(docker images -q reuse-api-worker-runner 2> /dev/null)" == "" ]]; then
  log "reuse-api-worker-runner Docker image does not exist."
  exit 42
fi

# Compose name for docker container derived from user__repo
# + limit to 255 characters in total (Docker limit)
# + add a short hash from the whole repository URL
# + replace invalid characters
DNAME_REPO="$(echo "$(basename "$(dirname "${REPO}")")__$(basename "${REPO}")" | cut -c -245)"
DNAME_HASH="$(echo "${REPO}" | xxh32sum | awk '{print $1}')"
DNAME="$(echo "${DNAME_REPO}__${DNAME_HASH}" | sed -E -e 's/^[^a-zA-Z0-9]//' -e 's/[^a-zA-Z0-9_.-]//g')"

# Create ENV file containing REUSE args
cat << EOF > "$TMP"
REUSE_GLOBAL_OPTIONS=${REUSE_GLOBAL_OPTIONS}
REUSE_LINT_OPTIONS=${REUSE_LINT_OPTIONS}
REUSE_SPDX_OPTIONS=${REUSE_SPDX_OPTIONS}
SEPARATOR=${DNAME}
EOF

# Run docker image and return status
docker run --env-file "$TMP" --name "${DNAME}" --rm reuse-api-worker-runner "${REPO}"
lint_status=$?

rm "$TMP"

log "Exit ${REPO} with ${lint_status}"

exit $lint_status
